#!/usr/bin/env python3

from datetime import datetime
import sys
import sqlite3
import subprocess

# Data stored in sqlite so it can be shared easily
tracker_db = sqlite3.connect('tracker_data.db')
db = tracker_db.cursor()
db.execute('''CREATE TABLE IF NOT EXISTS trackers
                (name text, day date, value real)''')
tracker_db.commit()


def error(message = None):
    if message is not None:
        print(message)
    exit(1)

def help():
    """Display usage information, exit program.
    """
    option = "  {:16} {}"
    help_text = [
        "Usage: tracker COMMAND [TRACKER_NAME] [ARGS]",
        "",
        "Commands:",
        option.format("help", "display this dialog"),
        option.format("update", "save new data to tracker"),
        option.format("list", "list available trackers"),
        option.format("delete", "remove tracker"),
        option.format("stats", "general statistics"),
        option.format("plot", "graphical representation"),
        "",
        option.format("Tracker Name", "title of data to track"),
        "",
        option.format("Args", "value to add to specified tracker"),
    ]
    print("\n".join(help_text))
    sys.exit(1)


def tracker_list():
    """Returns list of tracker names"""
    trackers = db.execute("SELECT DISTINCT name FROM trackers")
    names = [tup[0] for tup in trackers.fetchall()]
    return names


def tracker_exists(tracker, trackers = None):
    """Return whether given tracker exists

    Input:
        tracker: name of tracker to check
        trackers: optional list of trackers to determine existance with
    """
    if trackers is None:
        trackers = tracker_list()
    return tracker in trackers


def update_tracker(tracker_info):
    """Update tracker with new data

    Input:
        tracker_info: list in the form [tracker, data]
    """
    # Ensure tracker and data are provided
    if len(tracker_info) == 0:
        error("Must supply tracker and data to update")
    elif len(tracker_info) == 1:
        error("Must supply data to update '" + tracker_info[0] + "'")
    elif len(tracker_info) > 2:
        error("Too many arguments given for update command")

    # Ensure tracker exists
    tracker = tracker_info[0]
    if not tracker_exists(tracker):
        print("Tracker '" + tracker + "' not found")
        confirm = input("Type '" + tracker + "' to confirm creation: ").strip()
        if confirm != tracker:
            error("Update failed")

    # Ensure data is a number
    try:
        data = float(tracker_info[1])
    except ValueError:
        error("'" + tracker_info[1] + "' is not numerical, update failed")
    # Update existing row for today's value if possible
    db.execute('''UPDATE trackers SET value = value + :data
                    WHERE name = :tracker AND day=date('now', 'localtime')''',
                    {"data": data, "tracker": tracker})
    # Otherwise, insert a new row
    if not db.rowcount:
        db.execute("INSERT INTO trackers VALUES (?, date('now', 'localtime'), ?)",
                (tracker, data))
    tracker_db.commit()
    print("'" + tracker + "' updated")


def display_list(args = None):
    """Lists available trackers"""
    trackers = tracker_list()
    if len(trackers) == 0:
        print("No trackers found")
    else:
        print("Current Trackers:")
        tracker_option = "\t{}"
        for t in trackers:
            print(tracker_option.format(t))


def delete_tracker(tracker):
    """Delete existing tracker

    Input:
        tracker_info: existing tracker
    """
    # Ensure tracker is provided
    if len(tracker) != 1:
        error("Must supply tracker name to delete")
    tracker = tracker[0]
    if not tracker_exists(tracker):
        error("Cannot delete unknown tracker '" + tracker + "'")

    # User must confirm tracker to delete all entries
    confirm = input("Type '" + tracker + "' to confirm: ").strip()
    if confirm == tracker:
        db.execute("DELETE FROM trackers WHERE name=:tracker", {"tracker": tracker})
        tracker_db.commit()
        print("Tracker named '" + tracker + "' deleted")
    else:
        print("Deletion cancelled")


def display_stats(trackers):
    """Show stats for trackers

    Input:
        trackers: list of tracker names, empty implies global stats
    """
    if len(trackers) == 0:
        # number of trackers, number of elements in each tracker
        trackers = tracker_list()
        print(str(len(trackers)) + " tracker(s)")
        cursor = db.execute("SELECT * FROM trackers")
        entries = cursor.fetchall()
        print(str(len(entries)) + " total entries")

        for t in trackers:
            print()
            print(t)
            t_cursor = db.execute("SELECT * FROM trackers WHERE name=:name",
                    {'name': t})
            t_entries = cursor.fetchall()
            print("  " + str(len(t_entries)) + " entries")
    else:
        days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
        for t in trackers:
            if not tracker_exists(t):
                error("Cannot show stats for unknown tracker '" + t + "'")
            query = "SELECT * FROM TRACKERS where name=:tracker"
            cursor = db.execute(query, {"tracker": t})
            results = cursor.fetchall()
            num_entries = len(results)
            print(t + ": " + str(num_entries) + " entries")
            counts = [0,0,0,0,0,0,0]
            tally = [0,0,0,0,0,0,0]
            min_value = None
            max_value = None
            for r in results:
                count = r[2]
                day = datetime.strptime(r[1], "%Y-%m-%d").date()
                day_index = day.weekday()
                counts[day_index] += count
                tally[day_index] += 1
                if not min_value or min_value > count:
                    min_value = count
                if not max_value or max_value < count:
                    max_value = count

            point = "  {:3} -- {}"

            print(point.format("total", sum(counts)))
            print(point.format("average", sum(counts)/sum(tally)))
            print(point.format("min", min_value))
            print(point.format("max", max_value))

            print()

            print("  Totals\n  ======")
            for i in range(-1,6):
                print(point.format(days[i], str(counts[i])))

            print()

            print("  Averages\n  ========")
            for i in range(-1,6):
                if (tally[i] is 0):
                    print(point.format(days[i], 0))
                else:
                    print(point.format(days[i], str(counts[i]/tally[i])))


def display_plot(tracker):
    """Show plot for a tracker

    Input:
        tracker: tracker name to plot
    """
    if len(tracker) != 1:
        error("Only a single tracker can be plotted")
    else:
        tracker = tracker[0]
        if not tracker_exists(tracker):
            error("Cannot show stats for unknown tracker '" + tracker + "'")

        query = "SELECT * FROM TRACKERS where name=:tracker ORDER BY day ASC"
        cursor = db.execute(query, {"tracker": tracker})
        results = cursor.fetchall()

        # extract data for plotting
        dates = [r[1] for r in results]
        values = [v[2] for v in results]

        gnuplot = subprocess.Popen(["/usr/bin/gnuplot"], stdin=subprocess.PIPE)

        # give graph a size and title
        gnuplot.stdin.write("set term dumb 79 25\n".encode('utf-8'))
        gnuplot.stdin.write("set title '{}'\n".format(tracker).encode('utf-8'))

        # set date format for gnuplot
        gnuplot.stdin.write("set xdata time\n".encode('utf-8'))
        gnuplot.stdin.write('set timefmt "%Y-%m-%d\n'.encode('utf-8'))

        # lazy scaling, won't work nicely for all data ranges
        m = min(values) * .75
        mm = max(values) * 1.1
        gnuplot.stdin.write('set yrange[{}:{}]\n'.format(m, mm).encode('utf-8'))

        # plot data
        gnuplot.stdin.write("plot '-' using 1:2 title '{}' with impulses\n".format(tracker).encode('utf-8'))
        for d,v in zip(dates, values):
            s = "%s %f\n" % (d,v)
            gnuplot.stdin.write(s.encode('utf-8'))
        gnuplot.stdin.write("exit\n".encode('utf-8'))
        gnuplot.stdin.flush()


def handle_command(args):
    """Handles execution of valid commands
    """
    command = args[0]
    # TODO handle all possible commands
    # Map to command's handler function
    # Remaining args are passed regardless, dealt with in handler
    handlers = {
        "update" : update_tracker,
        "list"   : display_list,
        "delete" : delete_tracker,
        "stats"  : display_stats,
        "plot"   : display_plot
    }
    handlers[command](args[1:])


def validate_input():
    """Ensures user input contains valid commands
    """
    args = [arg.lower() for arg in sys.argv[1:]]

    # available commands
    # TODO consider consolidating with help(), handle_command
    commands = ["update", "list", "delete", "stats", "plot"]

    if len(args) == 0:
        help()
    if args[0] in ["help", "usage"]:
        help()
    if args[0] not in commands:
        error("Invalid command: '" + args[0] + "'")

    handle_command(args)
    

if __name__ == '__main__':
    validate_input()
